# Generated by Django 3.2.25 on 2024-08-06 04:47

from django.db import migrations, models
import newapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20240805_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=newapp.models.recipe_image_file_path),
        ),
    ]
